### PR TITLE
move awesome_print dependency to development

### PR DESCRIPTION
**Pull request by tierra**
This gem shouldn't be included as a production dependency.

### CODE REVIEW

**Comment by tierra** [comment]
See also realestate-com-au/pact#124

**Comment by bethesque** [comment]
Ooooh. Let me think about it. Most likely it's not used any more, but I just want to be sure it's not accidentally used in one of the other gems (it used to be all one gem, then got split out).

**Comment by bethesque** [comment]
Ok, I've found where it's used in pact-support, and pact-support requires the gem itself, so it's all good. Thank you!

**Comment by bethesque** [comment]
Oh, shit. Sorry, this is pact-support. This is what comes of trying to merge commits with two 9 month olds pulling on my legs. Revert revert!

**Comment by tierra** [comment]
Well, it's kind of the same problem as the pact gem. It's not going to bother me if this change is reverted, but they are two different patches for the same issue in separate gems.

**Comment by tierra** [comment]
Thanks for taking the time to look

**Comment by bethesque** [comment]
It's not used at all in the pact gem so I've accepted that PR, but the .ai method is used in pact-support at runtime here: https://github.com/bethesque/pact-support/blob/a103080972de55dbfa203245faadc7c02d64e5b2/lib/pact/matchers/list_diff_formatter.rb#L70

Thanks for submitting! Are you getting version conflicts?

**Pull request merged**
